context:
  version: "0.3.2"

package:
  name: llama-index-llms-azure-openai
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/l/llama-index-llms-azure-openai/llama_index_llms_azure_openai-${{ version }}.tar.gz
    sha256: c6ae4e6d896abc784a1d60e02a537c91e019317de69d02256424eab80c988646
  - url: https://raw.githubusercontent.com/run-llama/llama_index/main/LICENSE
    sha256: 24f40b5190fdacabc24ddbb5f76364d15e4f030925220ea300d8a2dd4993c8cb

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install .

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry-core
  run:
    - python >=${{ python_min }}
    - llama-index-llms-openai <0.4.0,>=0.3.0
    - azure-identity <2.0.0,>=1.15.0
    - httpx
    - llama-index-core <0.13.0,>=0.12.0

tests:
  - python:
      imports:
        - llama_index.llms.azure_openai
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/run-llama/llama_index
  summary: llama-index llms azure openai integration
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
